version: 2
updates:
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'deps(cargo)'
    groups:
      rust:
        patterns:
          - '*'
