version: 2
updates:
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'deps(cargo)'
    groups:
      rust:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'deps(ci)'
    groups:
      actions:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: '/web'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'deps(npm)'
    groups:
      actions:
        patterns:
          - '*'
