[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.6", features = ["postgres"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.9.7"
lazy_static = "1.5"
anyhow = "1.0"
