[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7.1", features = ["postgres", "runtime-tokio-native-tls"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.7.8"
lazy_static = "1.4"
anyhow = "1.0"
